### ISSUE TITLE
question: where to install this daemon

### ISSUE THREAD

**Issue by Ventusfahrer** [snip/flightLGo#1]
you wrote in Readme.md: 

...(can run on same host as running your OGN receiver)

Our OGN-Receiver has a very small bandwith on the network connection to the web. 

Do I understand the implementation of the flightLgo right: it does not connect to the airfields OGN-Receiver and can run on any host connected to the web?

kind regards

Peter

PS: after KTRAX charging for the Logbook, I am looking for an alternativ.

**Comment by snip** [comment]
> it does not connect to the airfields OGN-Receiver and can run on any host connected to the web?

Correct.

But it consume very very low bandwidth. So can still fit on same host as your receiver i think.
