### ISSUE TITLE
Flightlog is empty today, even though we had events reported.

### ISSUE THREAD

**Issue by Ventusfahrer** [snip/flightLGo#10]
![Bildschirmfoto von 2021-05-16 17-54-14](https://user-images.githubusercontent.com/5901190/118403673-cf459100-b66f-11eb-80c4-b7741fde9479.png)
![Bildschirmfoto von 2021-05-16 17-54-08](https://user-images.githubusercontent.com/5901190/118403684-d371ae80-b66f-11eb-891f-b9e6a522ad60.png)

Why?

**Comment by snip** [comment]
Maybe issue to join http://flightlog.glidernet.org/ from your host running flightLGo at this time?

**Comment by Ventusfahrer** [comment]
well, still having different issues when trying to access 

https://flightlog.glidernet.org/?airfield=Bensheim

often I got following error:
![Bildschirmfoto von 2021-06-29 19-31-03](https://user-images.githubusercontent.com/5901190/123843770-8c373880-d912-11eb-8d69-51f8ffad2dd5.png)

when I invoke 
https://flightlog.glidernet.org
without specifying the airfield  I almost get the page:
![Bildschirmfoto von 2021-06-29 18-39-26](https://user-images.githubusercontent.com/5901190/123843860-a1ac6280-d912-11eb-8737-2f5d1353a5c5.png)

othertimes the airfield list, but without Bensheim on the list.

On a different notebook, I still get  some content
![Bildschirmfoto von 2021-06-29 18-39-44](https://user-images.githubusercontent.com/5901190/123844087-e506d100-d912-11eb-9905-5ac9815793f2.jpg)

when stepping through the calendar there are only very view events (about 10) logged since 15 th of May.

Can it happen that there is a load-balancer misconfiguration the root cause? It would also lead into the situation that the log-entries are not delivered to the proper sql-nodes?

regards 

Peter

**Comment by snip** [comment]
This is beacause flightlog.glidernet.org is only expected to be accessible in http and not in https.
But this is something on which i can works on ...

**Comment by snip** [comment]
Issue fixed.
In fact it was an issue only in IPv6. No problem in IPv4.
