### ISSUE TITLE
Datetime Format

### ISSUE THREAD

**Issue by suesas** [snip/flightLGo#3]
Please include an option to display the takeoff and landing times in UTC.

**Comment by Ventusfahrer** [comment]
hi Seb,

I have attached an modified index.php which uses `<form>` elements to select the logbook date and dateformat for the output. It includes different types of dataformats (RFC, HH:MM:SS, HH:MM and their UTC variants).

Feel free to use it completly or only parts from it.

greets 

Peter

PS: information for ordinary users: the index.php is placed and executed on flightlog.glidernet.org. Therefore you can't use it by your own. You have the possibiltity to run your own flightlog WEB-Server. The details are not documented in detail, but all logbook specific parts needed are included in the _web_ folder. After setting the webserver up you will have to specify the complete URL in the parameter alternativeFlightLogURL in the .env configuration file. Your flights will then be stored to flightlog.glidernet.org and you webserver. On your own Web Logbook-server you can replace index.php by the attached one.
[index.php.zip](https://github.com/snip/flightLGo/files/5151002/index.php.zip)

**Comment by suesas** [comment]
Thank you very much Peter!
I will test it as soon as possible.

 Many greetings from EDNK

**Comment by snip** [comment]
Thanks @Ventusfahrer 
Maybe you can try to write a pull request? so it will be easier to manage/followup.

If not i will do it (or someone else can do it).

**Comment by Ventusfahrer** [comment]
Hi Seb,

I created a pull request.

I am still struggling a little with git. I did the changes on the forked repository for which I already created a pull request (installFlightLGoasService) without creating a branch. 

Is this the designed way for changes or do I have to create a fork every time I want to do additional changes?

Your help is welcome.

greets from the Frankfurt area.

**Comment by suesas** [comment]
unfortunately I don't have a lot experience with git either, but I think it should be fine.

**Comment by snip** [comment]
@Ventusfahrer yes it is better to start a new pull request each time with a fresh update from upstream master.
But it is ok this time i was able to get only required information.
I made 2 comments, maybe you can have a look to it and try to fix this?
https://github.com/snip/flightLGo/pull/4

Thanks for your contribution.

**Comment by snip** [comment]
Fixed with 520cdeee0e9fb2c20a19525a156c862c8a6c36fc

Thanks.
