### ISSUE TITLE
flightLGo shuts down every now and then

### ISSUE THREAD

**Issue by hanwe7** [snip/flightLGo#8]
I have installed flightLGo as a service according to the instructions at
https://github.com/snip/flightLGo/blob/master/contrib/installFlightLGoasService.md

Unfortunately the service stops every now and then and does not restart, sometimes after a few days or more often, sometimes after a few weeks or so. I have checked `/var/log/flightLGo/flightLGo.log` and the reason is usually connection timed out
`Mar 17 18:32:53 raspberrypi flightLGo[17294]: 2021/03/17 18:32:53 read tcp 192.168.8.229:36680->88.99.111.134:14580: read: connection timed out`
or EOF.
`Apr 26 07:59:18 localhost flightLGo[20841]: 2021/04/26 08:59:18 EOF`

It might be related to a shaky 3G mobile internet connection at a remote airfield. My workaround is to change in the service `/lib/systemd/system/flightLGo.service` from `Restart=on-failure` to `Restart=always`. This seems to restart the service when it is shut down by the errors above. 

(I also moved `StartLimitIntervalSec=60` from section `[Service]` to section `[Unit]` in the `/lib/systemd/system/flightLGo.service` file since I got another error message about this but should not be related to the shutdown issue.)

**Comment by snip** [comment]
Hi,

yes maybe related to a shaky 3G mobile internet connection.

Your changes looks good, maybe you can submit a pullrequest so this can be valuable for other users?

Thanks

**Comment by hanwe7** [comment]
Sure, I will try to submit a pull request. Probably later this week.
